title = "React Native 開発者向けガイド"
description = "このプロジェクトで React Native を使ってアプリケーションを開発する方に向けたドキュメントです。"
languageCode = "ja-jp"
hasCJKLanguage = true

relativeURLs = true
enableEmoji = true

theme = "github.com/themefisher/dot-hugo-documentation-theme"

sectionPagesMenu = "main"

[markup.goldmark.renderer]
# Markdownファイル内でHTMLタグを有効にする
unsafe = true

[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#4382bb"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/
