name: Auto-complete

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-complete:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: WIP
        uses: wip/action@v1.0.0
      - name: Auto-complete
        if: ${{ success() }}
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          MERGE_LABELS: '!skip-auto-complete,!wip'
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_FORKS: false
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 30000
          MERGE_DELETE_BRANCH: true
          UPDATE_LABELS: '!skip-auto-update,!wip'
          UPDATE_METHOD: merge
          UPDATE_RETRIES: 10
          UPDATE_RETRY_SLEEP: 30000
