name: WIP
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
  status: {}

jobs:
  wip:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: WIP
        uses: "wip/action@v1.0.0"
